### ISSUE TITLE
Timeout creating the gosu key?

### ISSUE THREAD

**Issue by kcantrel** [GoogleCloudPlatform/mongodb-docker#2]
When doing a "docker build" with the Dockerfile I get the following error:

```
+ export GNUPGHOME=/tmp/tmp.KLtrZm8P4q
+ gpg --keyserver pgp.mit.edu --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: keyring `/tmp/tmp.KLtrZm8P4q/secring.gpg' created
gpg: keyring `/tmp/tmp.KLtrZm8P4q/pubring.gpg' created
gpg: requesting key BF357DD4 from hkp server pgp.mit.edu
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error

```
I know know if there is temporary or not, but it clearly isn't working right now.``

**Comment by huyhg** [comment]
This should be transient. Our solution is to retry... We actually tried a few key servers and none of them are 100% reliable. `mit.edu` so far is better than the others.
